# -*- coding: utf-8 -*-

# NAME_TRANSLATIONS is a mapping of the file names from the extracted specification
# archive to valid Python class names.

NAME_TRANSLATIONS = {
    "accountupdate": "AccountUpdate",
    "activate": "Activate",
    "administration": "Administration",
    "arrival": "Arrival",
    "authresponse": "AuthResponse",
    "authreview": "AuthReview",
    "availableslots": "AvailableSlots",
    "availableslotsresponse": "AvailableSlotsResponse",
    "booked": "Booked",
    "bookedresponse": "BookedResponse",
    "cancel": "Cancel",
    "censusquery": "CensusQuery",
    "censusqueryresponse": "CensusQueryResponse",
    "deactivate": "Deactivate",
    "delete": "Delete",
    "deplete": "Deplete",
    "discharge": "Discharge",
    "documentget": "DocumentGet",
    "documentgetresponse": "DocumentGetResponse",
    "documentquery": "DocumentQuery",
    "documentqueryresponse": "DocumentQueryResponse",
    "groupedorders": "GroupedOrders",
    "locationquery": "LocationQuery",
    "locationqueryresponse": "LocationQueryResponse",
    "modification": "Modification",
    "modify": "Modify",
    "new": "New",
    "newpatient": "NewPatient",
    "newunsolicited": "NewUnsolicited",
    "noshow": "NoShow",
    "patientmerge": "PatientMerge",
    "patientpush": "PatientPush",
    "patientquery": "PatientQuery",
    "patientqueryresponse": "PatientQueryResponse",
    "patientupdate": "PatientUpdate",
    "payment": "Payment",
    "paymentbatch": "PaymentBatch",
    "preadmit": "PreAdmit",
    "providerquery": "ProviderQuery",
    "providerqueryresponse": "ProviderQueryResponse",
    "pushslots": "PushSlots",
    "query": "Query",
    "queryresponse": "QueryResponse",
    "registration": "Registration",
    "replace": "Replace",
    "request": "Request",
    "reschedule": "Reschedule",
    "response": "Response",
    "sign-on": "SignOn",
    "study": "Study",
    "subjectupdate": "SubjectUpdate",
    "submission": "Submission",
    "submissionbatch": "SubmissionBatch",
    "transaction": "Transaction",
    "transfer": "Transfer",
    "update": "Update",
    "visitmerge": "VisitMerge",
    "visitpush": "VisitPush",
    "visitquery": "VisitQuery",
    "visitqueryresponse": "VisitQueryResponse",
    "visitupdate": "VisitUpdate",
}
