exclude: >
  (?x)(
    \.egg-info
  )$
repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
    name: Finding third party Python imports
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    name: Reorder Python imports
    additional_dependencies: ['toml']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-merge-conflict
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
  - id: python-check-mock-methods
  - id: python-no-eval
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: _datetime\.py|docs|tests
    args: ["--ignore=E501,D104,D105,W503"]
    additional_dependencies: ['pep8-naming']
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.10
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pytest
    language: system
    files: 'tests/.*'
    pass_filenames: false
