exclude: >
  (?x)(
    \.egg-info
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
  - id: python-check-mock-methods
  - id: python-no-eval
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: _datetime\.py|docs|tests
    args: ["--ignore=E501,D104,D105,W503"]
    additional_dependencies: ['pep8-naming']
- repo: https://github.com/omnilib/ufmt
  rev: v2.0.0b1
  hooks:
  - id: ufmt
    exclude: "tests/snapshots/.*"
- repo: local
  hooks:
  - id: tox
    name: tox
    entry: tox
    language: system
    files: 'tests/.*'
    pass_filenames: false
