on:
  schedule:
    # Run this every Sunday at 7:15
    - cron: '15 7 * * 0'

jobs:
  check_for_updated_schema:
    runs-on: ubuntu-latest
    steps:
      # Check out and set up redox_lib_gen
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: redox_lib_gen

      - name: Change dir to redox_lib_gen
        run: cd redox_lib_gen

      - name: Install Python and Poetry
        uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: 3.10

      - name: Set up poetry virtualenv
        run: poetry install

      - run: cd ..

      # Check out and set up pyredox
      - name: Checkout pyredox
        uses: actions/checkout@v3
        with:
          repository: cedar/pyredox
          path: pyredox

      - name: Change dir to pyredox
        run: cd pyredox

      - name: Install Python and Poetry
        uses: ITProKyle/action-setup-python@v0.1.0
        with:
          python-version: 3.6

      - name: Set up poetry virtualenv
        run: poetry install

      - run: cd ..

      # Run generator, handle updates
      - name: Generate fresh version of library
        run: |
          cd redox_lib_gen/redox_lib_gen
          poetry run generate.py --force-download
          cd -

      - name: Open PR if there are changes
        run: |
          cd redox_lib_gen/redox_lib_gen
          poetry run pull_request.py
          cd -
#        env:
#          GITHUB_TOKEN: ${{ secrets.PYREDOX_GITHUB_TOKEN }}
